<?php
/* This file was automatically generated by the `grunt public-cachebuster` command (Mon Feb 17 2020 13:30:13 GMT+0000 (Coordinated Universal Time)). */
return array(
	'public/dist/admin.js' => 'f304f75696ec25f73d8fecefe4a3c412',
	'public/dist/admin.css' => 'c7af1be91214898f5d685d7af6744f91',
	'public/dev/admin.js' => 'c51f6fe5fc8ac58e178bb74869f1f3d3',
	'public/dev/admin.css' => '9fd3a01e93ff432459868c4c04f97631',
);
